name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - ".dependabot/**"
      - ".vscode/**"
    branches-ignore:
      - "dependabot/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".dependabot/**"
      - ".vscode/**"

jobs:
  Test:
    name: ${{ matrix.os }} - node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Test without Jest (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: "xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' npm run test-no-jest"
      - name: Test with Jest (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: "xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' npm run test"
      - name: Test without Jest (Windows & MacOS)
        if: matrix.os != 'ubuntu-latest'
        run: npm run test-no-jest
      - name: Test with Jest (Windows & MacOS)
        if: matrix.os != 'ubuntu-latest'
        run: npm run test
